const constants = {
    BNTDESTRUCTIVE : 'destructive',
    BTNNEUTRAL : 'outline-brand',
    BTNSUCCESS : 'neutral',
    CHECKEDIN : 'Available',
    CHECKEDINCLS : 'slds-var-p-around_medium slds-align_absolute-center available availablebg',
    CHECKEDOUT : 'Unavailable',
    CHECKEDOUTCLS : 'slds-var-p-around_medium slds-align_absolute-center unavailable unavailablebg',
    CHECKIN : 'Check In',
    CHECKINTXT : 'By checking in you will make yourself available for work assignments.',
    CHECKLOC : ' Your location as shown on the map will be shared.',
    CHECKONLINE : ' This update will be submitted only if the device is online. Please make sure the device is online.',
    CHECKOUT : 'Check Out',
    CHECKOUTCONFIRM : 'Are you sure you want to check out? You still have appointments assigned to you for today. By checking out these appointments will be set to in jeopardy!',
    CHECKOUTTXT : 'By checking out you will make yourself unavailable for any new work assignments.',
    CURRENTLOC : 'Your current location and of the appointments',
    INJEOPARDYREASON : 'Assigned Resource Checked Out',
    NUMOFAPPNTS : 'Number of appointments todo for today: ',
    RETRIEVINGSTATUS : 'Retrieving status...',
    UPDATESUCCESS : 'Your update was successful, you can close this action.',
    THANKYOU : 'This action will be automatically closed in 5 seconds...',
    LOCSRVNOTAVAILABLE : 'LocationService API not available!',
};

export default constants;